### ISSUE TITLE
App force quits when tapping on any contact

### ISSUE THREAD

**Issue by The-Linux-User** [Chooloo/koler#210]
## Checklist

- [x] I am using the latest version - x.xx.x 
- [X] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [X] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Open App 
2. Choose "Contacts" view
3. Tap on any contact

### Actual behaviour
The app force quits

### Expected behavior
It shows contact info / dials number, app stays open

### Device info
 - Android version/Custom ROM version: Android 11 OxygenOS
 - Device model: OnePlus 8

**Comment by roeiedri** [comment]
Can you send a video showing that behaviour?

**Comment by The-Linux-User** [comment]
Is there a way to send it to you privately since I don't wat to put the names of my contacts openly on the internet.

**Comment by roeiedri** [comment]
Of course you can send it to my email

**Comment by The-Linux-User** [comment]
Hi,
Here is a link to the screen recording:
https://www.jottacloud.com/share/aefk4booq3jk
Hope it works.

-------- Original-Nachricht --------

**Comment by adguardgirl** [comment]
I have the same issue. Clicking on a contact crashed the app. After relaunching the app and trying it again, clicking on a contact closes the app. Tried version 107 and 106. Android 11, latest version, pixel 5.

**Comment by roeiedri** [comment]
Maybe you didnt set koler as the default dialer? I fixed that bug today

**Comment by The-Linux-User** [comment]
Well that fixed it!
I didn't know that you have to set it as the default dialer.
My other bug report (app crashes when scrolling through recents fast) is still present.

Thanks for the info!

-------- Original-Nachricht --------

**Comment by adguardgirl** [comment]
That fixed it.

**Comment by roeiedri** [comment]
Fixed on latest version, will upload a new release today.
